# Alias
alias update="brew update"
alias upgrade="brew upgrade"
alias cleanup="brew cleanup"
alias ls="eza -lahF --tree --level=1 --color=always --icons --sort=name --group-directories-first --no-time --no-user --no-filesize --git --no-permissions"
alias v="nvim"
alias lg="lazygit"
alias man="man -P 'nvim +Man!'"
alias startpyenv="source ~/.venv/bin/activate"
alias fastfetch="fastfetch --logo-color-1 magenta --logo $HOME/.config/fastfetch/logo/not-gui.txt"
alias pipes="$HOME/.scripts/pipes.sh"
alias spf="spf -c $HOME/.config/superfile/config.toml"
