[manager]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = true
sort_dir_first = true
linemode = "mtime"
show_hidden = true
show_symlink = true

[preview]
max_width = 800
max_height = 500

[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'imv "$@"', desc = "Open" },
]
extract = [
	{ run = 'unzip "$1"', desc = "Extract here", for = "unix" },
]

pdf = [
    {run = 'zathura "$1"', desc = "View PDF", for = "unix"}
]

[open]
prepend_rules = [
    {name = "*.pdf", use = "pdf"},
]
