set -g default-terminal "tmux-256color"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# binding for horizontal split command 
unbind %
bind | split-window -h

# binding for vertical split command 
unbind '"'
bind - split-window -v

# binding to reload the tmux
unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# vim binding for navigating the panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

# vim binding for  copying the text from the tmux
set-window-option -g mode-keys vi

bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# setting the mouse on for tmux
set -g mouse on

# default indexing to 1
set -g history-limit 10000
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

# status bar in top
set -g status-position top

# tpm plugin
set -g @plugin 'tmux-plugin/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'

# theme
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_uptime}"


# Initialize tmux plugin manager AKA tpm (keep this line at the very bottom of the config)
run '~/.tmux/plugins/tpm/tpm'
